name: CI
on:
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - .sbtopts
      - build.sbt
      - .scalafmt.conf
      - project/**
      - src/**

permissions:
  packages: read
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  code-check:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
      options: --user 1001:1001
    steps:
      - uses: actions/checkout@v4
      - run: sbt headerCheckAll
  test:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
      options: --user 1001:1001
    steps:
      - uses: actions/checkout@v4
      - run: |
          env
          sbt clean test
  docker-buid:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: .github/scripts/dnd-sbt docker/Docker/publishLocal
