name: Security Scan
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

#env:
#  REPORT_DIR: security-reports
#  GITHUB_TOKEN: ${{ github.token }}

jobs:
  security-scan:
    name: Security Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: raw-labs/das-sec-scan@main
        with:
          severity: CRITICAL,HIGH,MEDIUM,LOW
          github-token: ${{ github.token }}
